version: '2.3'

services:
  pd0:
    image: pingcap/pd:v2.0.9
    ports:
      - "2379:2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data/pd0:/data
      - ./log/pd0:/log
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --config=/pd.toml
      - --data-dir=/data
      - --log-file=/log/pd.log
    restart: on-failure
  zk0:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - ./data/zk0/data:/data
      - ./data/zk0/datalog:/datalog
    restart: on-failure
  kafka0:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka0"
      KAFKA_ZOOKEEPER_CONNECT: zk0:2181
      KAFKA_MESSAGE_MAX_BYTES: 20000000
      KAFKA_LOG_DIRS: /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka0:/data
      - ./log/kafka0:/opt/kafka/logs
    depends_on:
      - "zk0"
    restart: on-failure
  tikv0:
    image: pingcap/tikv:v2.0.9
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data/tikv0:/data
      - ./log/tikv0:/log
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --pd=pd0:2379
      - --config=/tikv.toml
      - --data-dir=/data
      - --log-file=/log/tikv.log
    depends_on:
      - "pd0"
    restart: on-failure
  pump0:
    image: pingcap/tidb-binlog:v2.0.9
    ports:
      - "8250:8250"
    volumes:
      - ./config/pump.toml:/pump.toml:ro
      - ./data/pump0:/data
      - ./log/pump0:/log
      - ./tmp:/tmp
    command:
      - /pump
      - --addr=pump0:8250
      - --pd-urls=http://pd0:2379
      - --kafka-addrs=kafka0:9092
      - --socket=unix:///tmp/pump.sock
      - --config=/pump.toml
      - --data-dir=/data
      - --log-file=/log/pump.log
    depends_on:
      - "pd0"
      - "tikv0"
      - "kafka0"
    restart: on-failure
  tidb0:
    image: pingcap/tidb:v2.0.9
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./tmp:/tmp
      - ./log/tidb0:/log
    command:
      - --store=tikv
      - --path=pd0:2379
      - --binlog-socket=/tmp/pump.sock
      - --config=/tidb.toml
      - --log-file=/log/tidb.log
    depends_on:
      - "tikv0"
      - "pump0"
    restart: on-failure
  tidb1:
    image: pingcap/tidb:v2.0.9
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./tmp:/tmp
      - ./log/tidb0:/log
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - --log-file=/log/tidb.log
    depends_on:
      - "tikv0"
    restart: on-failure
  drainer0:
    image: pingcap/tidb-binlog:v2.0.9
    ports:
      - "8249:8249"
    extra_hosts:
      - "ch:${HOST_IP}"
    volumes:
      - ./config/drainer.toml:/drainer.toml:ro
      - ./data/drainer0:/data
      - ./log/drainer0:/log
    command:
      - /drainer
      - --addr=drainer0:8249
      - --pd-urls=http://pd0:2379
      - --kafka-addrs=kafka0:9092
      - --config=/drainer.toml
      - --data-dir=/data
      - --log-file=/log/drainer.log
    depends_on:
      - "pump0"
    restart: on-failure
