global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'tidb-cluster'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          cluster: 'tidb-cluster'
          # - targets: ['tiflash0:8234']
      - targets: ['192.168.65.2:8234']
        labels:
          cluster: 'tiflash-cluster'
rule_files:
  - 'pd.rules.yml'
  - 'tikv.rules.yml'
  - 'tidb.rules.yml'
